### ISSUE TITLE
Inconsistent metrics deploying a Next.js app

### ISSUE THREAD

**Issue by jonathanwelton** [netlify/netlify-plugin-lighthouse#189] opened 2021-04-27 11:46 UTC
When I run the Google Chrome Lighthouse plugin against my deployed site everything looks good: Performance, Accessibility, Best Practices and SEO all report scores of 90-100.

However, when the Netlify plugin runs, these numbers are invariably lower, especially with regards to Performance:

```
Expected category Performance to be greater or equal to 0.9 but got 0.63
   'First Contentful Paint' received a score of 0.95
   'Speed Index' received a score of 0.99
   'Largest Contentful Paint' received a score of 0.25
   'Time to Interactive' received a score of 0.75
   'Total Blocking Time' received a score of 0.65
   'Cumulative Layout Shift' received a score of 0.03
```

I keep reducing the Performance threshold to get the build passing, but that's obviously not a great solution.

Is this related to the fact that I'm deploying a Next.js app?

**Comment by erezrokah** [comment] 2021-04-27 12:19
Hi @jonathanwelton, I don't think it is related to it being a Next.js app.

The plugin runs the audit on a local http serve and not on the live site, so that might explain some differences.
Also, the plugin runs in the Netlify build system, while you're probably running Lighthouse from your own machine.

To simulate the plugin run locally you can use our CLI:
1. `npm install -g netlify-cli`
2. `netlify login`
3. `netlify link` from the repo directory
4. `netlify build` and it should simulate the build locally

Do you have a public repo you can share or a way that can help us reproduce the issue? That will help a lot in finding a solution

**Comment by jonathanwelton** [comment] 2021-04-29 14:02
Hi @erezrokah, sorry for the delayed response.

Unfortunately it's for a work project, so the repo is private.

I've tried running the commands you listed to simulate the plugin locally, but it doesn't appear to analyse anything:

`────────────────────────────────────────────────────────────────
  2. onPostBuild command from @netlify/plugin-lighthouse
────────────────────────────────────────────────────────────────
​
Serving and scanning site from directory out
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +508ms
  ChromeLauncher Waiting for browser.....√ +3ms
  ChromeLauncher Killing Chrome instance 27244 +27ms
​
(@netlify/plugin-lighthouse onPostBuild completed in 813ms)`

Do I need to configure anything extra?

**Comment by erezrokah** [comment] 2021-04-29 14:08
H @jonathanwelton.

> Unfortunately it's for a work project, so the repo is private.

Is it possible to create another public repo that reproduces the issue? 

> Do I need to configure anything extra?

You shouldn't need to configure anything else, can you share the full log of the `netlify build` command?

**Comment by jonathanwelton** [comment] 2021-04-29 14:10
@erezrokah here it is:

```
> next build

(node:24192) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Source\anw.acquisition\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Loaded env from C:\Source\anw.acquisition\.env.production
warn  - Detected next.config.js, no exported configuration found. https://err.sh/vercel/next.js/empty-configuration
info  - Using external babel configuration from C:\Source\anw.acquisition\.babelrc
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (5/5)
info  - Finalizing page optimization

Page                                                           Size     First Load JS
┌ ○ /                                                          377 B           107 kB
├   /_app                                                      0 B             107 kB
├ ○ /404                                                       3.46 kB         110 kB
└ ● /browse/m/track/[slug]                                     2.35 kB         109 kB
    ├ /browse/m/track/sleepless-daze_1035198
    └ /browse/m/track/purple-beat_1008534
+ First Load JS shared by all                                  107 kB
  ├ chunks/44dec107c629fb51b77c176a452949187e0451e4.32dd51.js  26.9 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.55ee14.js  13.1 kB
  ├ chunks/framework.691eee.js                                 42.1 kB
  ├ chunks/main.016968.js                                      7.07 kB
  ├ chunks/pages/_app.a19a4e.js                                16.8 kB
  └ chunks/webpack.50bee0.js                                   751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)


> anw.acquisition@0.1.0 export
> next export

info  - Loaded env from C:\Source\anw.acquisition\.env.production
warn  - Detected next.config.js, no exported configuration found. https://err.sh/vercel/next.js/empty-configuration
info  - using build directory: C:\Source\anw.acquisition\.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 11 workers
info  - Copying "public" directory
info  - Exporting (2/2)
Export successful. Files written to C:\Source\anw.acquisition\out
​
(build.command completed in 16.1s)
​
────────────────────────────────────────────────────────────────
  2. onPostBuild command from @netlify/plugin-lighthouse
────────────────────────────────────────────────────────────────
​
Serving and scanning site from directory out
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +508ms
  ChromeLauncher Waiting for browser.....√ +3ms
  ChromeLauncher Killing Chrome instance 27244 +27ms
​
(@netlify/plugin-lighthouse onPostBuild completed in 813ms)
​
────────────────────────────────────────────────────────────────
  Summary
────────────────────────────────────────────────────────────────
​
> Plugin @netlify/plugin-lighthouse ran successfully
  Summary for directory 'out': undefined
​
────────────────────────────────────────────────────────────────
  Netlify Build Complete
────────────────────────────────────────────────────────────────
​
(Netlify Build completed in 17.7s)
```

**Comment by erezrokah** [comment] 2021-04-29 14:52
Thanks @jonathanwelton that's helpful. Can you share the output of `npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli`?

Looks like like Lighthouse is running, but not returning any results.

**Comment by jonathanwelton** [comment] 2021-04-29 15:10
@erezrokah here it is:

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 6.09 GB / 15.84 GB
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by erezrokah** [comment] 2021-04-29 16:35
Thanks @jonathanwelton, can you share a public repo so I can try this on my machine?

Also, can you trying using Lighthouse as a CLI and see if that works?
https://github.com/GoogleChrome/lighthouse#using-the-node-cli

The reason behind it is to understand if this is an issue with Lighthouse or the plugin.

Another option is to try with Node.js 15

**Comment by jonathanwelton** [comment] 2021-04-30 17:27
@erezrokah I tried adding the Lighthouse CLI to the project, and running Lighthouse in a local Netlify plugin, post-deployment. 

Interestingly, I got the same results.

Configuring Lighthouse to have 5 runs, the Performance metric always changed:

```
6:12:50 PM:   ✘  categories.performance failure for minScore assertion
6:12:50 PM:         expected: >=0.9
6:12:50 PM:            found: 0.84
6:12:50 PM:       all values: 0.8, 0.79, 0.84, 0.83, 0.81
6:12:50 PM:   ✅  categories.accessibility passing for minScore assertion
6:12:50 PM:         expected: >=0.9
6:12:50 PM:            found: 0.96
6:12:50 PM:       all values: 0.96, 0.96, 0.96, 0.96, 0.96
6:12:50 PM:   ✅  categories.best-practices passing for minScore assertion
6:12:50 PM:         expected: >=0.9
6:12:50 PM:            found: 1
6:12:50 PM:       all values: 1, 1, 1, 1, 1
6:12:50 PM:   ✅  categories.seo passing for minScore assertion
6:12:50 PM:         expected: >=0.9
6:12:50 PM:            found: 0.92
6:12:50 PM:       all values: 0.92, 0.92, 0.92, 0.92, 0.92
```

This document alludes to why that might be: https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md

What's frustrating is that, as mentioned before, the Google Chrome Lighthouse plugin always reports good numbers, and now I'm testing against exactly the same site!

Maybe performance drops for the first request, and there's some kind of warm-up call I could make before Lighthouse starts?

**Comment by erezrokah** [comment] 2021-05-03 13:37
Thanks for the additional information.

Maybe some of the settings of the Google Chrome Lighthouse plugin impact this:
![image](https://user-images.githubusercontent.com/26760571/116882956-b7ace800-ac2d-11eb-89c2-cf6b8c97adcc.png)

Can you try with various settings?

**Comment by jonathanwelton** [comment] 2021-05-11 08:42
@erezrokah Sorry for the late reply, but I couldn't reproduce the low Performance score using the Google Chrome Lighthouse plugin. Performance scores higher on Desktop than Mobile, but in both cases they are 90 or above. 

What device does the Netlify plugin run using?

**Comment by erezrokah** [comment] 2021-05-11 09:19
Hi @jonathanwelton, we use the default which is Mobile, see reasoning [here](https://web.dev/lighthouse-whats-new-6.0/#emulation).

To confirm, this issue happens with the Lighthouse CLI too, without the plugin?

If so, maybe we can try opening an issue on the Lighthouse repo?
I think that would require sharing a URL/repo that allows reproducing the issue.

**Comment by jackbrewer** [comment] 2022-10-31 11:41
Hey, I'm closing this as it's not been updated for a while.

If you're still using this Lighthouse plugin, v4 adds the ability to view full Lighthouse reports in the Netlify UI ([read more in the docs](https://docs.netlify.com/monitor-sites/lighthouse/)). This allows for a much more detailed review of any audits which vary between platforms. The settings used for each run can be found in the footer of the Lighthouse report.

**Closed by jackbrewer** 2022-10-31 11:41 UTC
Labels: type: bug
